package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiethoadonnhap generated by hbm2java
 */
@Entity
@Table(name="CHITIETHOADONNHAP"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class Chitiethoadonnhap  implements java.io.Serializable {


     private String maCthdn;
     private Hoadonnhap hoadonnhap;
     private Nguyenlieu nguyenlieu;
     private BigDecimal donGia;
     private int sl;
     private BigDecimal thanhTien;

    public Chitiethoadonnhap() {
    }

    public Chitiethoadonnhap(String maCthdn, Hoadonnhap hoadonnhap, Nguyenlieu nguyenlieu, BigDecimal donGia, int sl, BigDecimal thanhTien) {
       this.maCthdn = maCthdn;
       this.hoadonnhap = hoadonnhap;
       this.nguyenlieu = nguyenlieu;
       this.donGia = donGia;
       this.sl = sl;
       this.thanhTien = thanhTien;
    }
   
     @Id 

    
    @Column(name="MaCTHDN", unique=true, nullable=false, length=10)
    public String getMaCthdn() {
        return this.maCthdn;
    }
    
    public void setMaCthdn(String maCthdn) {
        this.maCthdn = maCthdn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaHDN", nullable=false)
    public Hoadonnhap getHoadonnhap() {
        return this.hoadonnhap;
    }
    
    public void setHoadonnhap(Hoadonnhap hoadonnhap) {
        this.hoadonnhap = hoadonnhap;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaNL", nullable=false)
    public Nguyenlieu getNguyenlieu() {
        return this.nguyenlieu;
    }
    
    public void setNguyenlieu(Nguyenlieu nguyenlieu) {
        this.nguyenlieu = nguyenlieu;
    }

    
    @Column(name="DonGia", nullable=false, scale=4)
    public BigDecimal getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }

    
    @Column(name="SL", nullable=false)
    public int getSl() {
        return this.sl;
    }
    
    public void setSl(int sl) {
        this.sl = sl;
    }

    
    @Column(name="ThanhTien", nullable=false, scale=4)
    public BigDecimal getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(BigDecimal thanhTien) {
        this.thanhTien = thanhTien;
    }




}


