package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cthd generated by hbm2java
 */
@Entity
@Table(name="CTHD"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class Cthd  implements java.io.Serializable {


     private String maCthd;
     private HoaDon hoaDon;
     private Monan monan;
     private int sl;
     private BigDecimal thanhTien;
     private BigDecimal donGia;

    public Cthd() {
    }

    public Cthd(String maCthd, HoaDon hoaDon, Monan monan, int sl, BigDecimal thanhTien, BigDecimal donGia) {
       this.maCthd = maCthd;
       this.hoaDon = hoaDon;
       this.monan = monan;
       this.sl = sl;
       this.thanhTien = thanhTien;
       this.donGia = donGia;
    }
   
     @Id 

    
    @Column(name="MaCTHD", unique=true, nullable=false, length=5)
    public String getMaCthd() {
        return this.maCthd;
    }
    
    public void setMaCthd(String maCthd) {
        this.maCthd = maCthd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaHD", nullable=false)
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaMon")
    public Monan getMonan() {
        return this.monan;
    }
    
    public void setMonan(Monan monan) {
        this.monan = monan;
    }

    
    @Column(name="SL", nullable=false)
    public int getSl() {
        return this.sl;
    }
    
    public void setSl(int sl) {
        this.sl = sl;
    }

    
    @Column(name="ThanhTien", nullable=false, scale=4)
    public BigDecimal getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(BigDecimal thanhTien) {
        this.thanhTien = thanhTien;
    }

    
    @Column(name="DonGia", nullable=false, scale=4)
    public BigDecimal getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }




}


