package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DangNhap generated by hbm2java
 */
@Entity
@Table(name="DangNhap"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class DangNhap  implements java.io.Serializable {


     private int maDangNhap;
     private String taiKhoan;
     private String matKhau;
     private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);

    public DangNhap() {
    }

	
    public DangNhap(int maDangNhap, String taiKhoan, String matKhau) {
        this.maDangNhap = maDangNhap;
        this.taiKhoan = taiKhoan;
        this.matKhau = matKhau;
    }
    public DangNhap(int maDangNhap, String taiKhoan, String matKhau, Set<NhanVien> nhanViens) {
       this.maDangNhap = maDangNhap;
       this.taiKhoan = taiKhoan;
       this.matKhau = matKhau;
       this.nhanViens = nhanViens;
    }
   
     @Id 

    
    @Column(name="MaDangNhap", unique=true, nullable=false)
    public int getMaDangNhap() {
        return this.maDangNhap;
    }
    
    public void setMaDangNhap(int maDangNhap) {
        this.maDangNhap = maDangNhap;
    }

    
    @Column(name="TaiKhoan", nullable=false, length=10)
    public String getTaiKhoan() {
        return this.taiKhoan;
    }
    
    public void setTaiKhoan(String taiKhoan) {
        this.taiKhoan = taiKhoan;
    }

    
    @Column(name="MatKhau", nullable=false, length=10)
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dangNhap")
    public Set<NhanVien> getNhanViens() {
        return this.nhanViens;
    }
    
    public void setNhanViens(Set<NhanVien> nhanViens) {
        this.nhanViens = nhanViens;
    }




}


