package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Duockhuyenmai generated by hbm2java
 */
@Entity
@Table(name="Duockhuyenmai"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class Duockhuyenmai  implements java.io.Serializable {


     private String maDkm;
     private KhuyenMai khuyenMai;
     private Monan monan;
     private Date thoiGianBd;
     private Date thoigianKt;

    public Duockhuyenmai() {
    }

    public Duockhuyenmai(String maDkm, KhuyenMai khuyenMai, Monan monan, Date thoiGianBd, Date thoigianKt) {
       this.maDkm = maDkm;
       this.khuyenMai = khuyenMai;
       this.monan = monan;
       this.thoiGianBd = thoiGianBd;
       this.thoigianKt = thoigianKt;
    }
   
     @Id 

    
    @Column(name="MaDKM", unique=true, nullable=false, length=5)
    public String getMaDkm() {
        return this.maDkm;
    }
    
    public void setMaDkm(String maDkm) {
        this.maDkm = maDkm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaKM", nullable=false)
    public KhuyenMai getKhuyenMai() {
        return this.khuyenMai;
    }
    
    public void setKhuyenMai(KhuyenMai khuyenMai) {
        this.khuyenMai = khuyenMai;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaMon")
    public Monan getMonan() {
        return this.monan;
    }
    
    public void setMonan(Monan monan) {
        this.monan = monan;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ThoiGianBD", nullable=false, length=10)
    public Date getThoiGianBd() {
        return this.thoiGianBd;
    }
    
    public void setThoiGianBd(Date thoiGianBd) {
        this.thoiGianBd = thoiGianBd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ThoigianKT", nullable=false, length=10)
    public Date getThoigianKt() {
        return this.thoigianKt;
    }
    
    public void setThoigianKt(Date thoigianKt) {
        this.thoigianKt = thoigianKt;
    }




}


