package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name="HoaDon"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class HoaDon  implements java.io.Serializable {


     private String maHd;
     private BanAn banAn;
     private NhanVien nhanVien;
     private Date ngayTao;
     private String ghiChu;
     private BigDecimal tongTien;
     private Set<Cthd> cthds = new HashSet<Cthd>(0);

    public HoaDon() {
    }

	
    public HoaDon(String maHd, BanAn banAn, NhanVien nhanVien, Date ngayTao, String ghiChu) {
        this.maHd = maHd;
        this.banAn = banAn;
        this.nhanVien = nhanVien;
        this.ngayTao = ngayTao;
        this.ghiChu = ghiChu;
    }
    public HoaDon(String maHd, BanAn banAn, NhanVien nhanVien, Date ngayTao, String ghiChu, BigDecimal tongTien, Set<Cthd> cthds) {
       this.maHd = maHd;
       this.banAn = banAn;
       this.nhanVien = nhanVien;
       this.ngayTao = ngayTao;
       this.ghiChu = ghiChu;
       this.tongTien = tongTien;
       this.cthds = cthds;
    }
   
     @Id 

    
    @Column(name="MaHD", unique=true, nullable=false, length=5)
    public String getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(String maHd) {
        this.maHd = maHd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaBan", nullable=false)
    public BanAn getBanAn() {
        return this.banAn;
    }
    
    public void setBanAn(BanAn banAn) {
        this.banAn = banAn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaNV")
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayTao", nullable=false, length=10)
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

    
    @Column(name="GhiChu", nullable=false)
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }

    
    @Column(name="TongTien", scale=4)
    public BigDecimal getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(BigDecimal tongTien) {
        this.tongTien = tongTien;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hoaDon")
    public Set<Cthd> getCthds() {
        return this.cthds;
    }
    
    public void setCthds(Set<Cthd> cthds) {
        this.cthds = cthds;
    }




}


