package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable ;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name="KhachHang"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class KhachHang  implements java.io.Serializable  {


     private String maKh;
     private String tenKh;
     private String sdt;
     private Set<DatBan> datBans = new HashSet<DatBan>(0);

    public KhachHang() {
    }

	
    public KhachHang(String maKh, String tenKh, String sdt) {
        this.maKh = maKh;
        this.tenKh = tenKh;
        this.sdt = sdt;
    }
    public KhachHang(String maKh, String tenKh, String sdt, Set<DatBan> datBans) {
       this.maKh = maKh;
       this.tenKh = tenKh;
       this.sdt = sdt;
       this.datBans = datBans;
    }
   
     @Id 

    
    @Column(name="MaKH", unique=true, nullable=false, length=5)
    public String getMaKh() {
        return this.maKh;
    }
    
    public void setMaKh(String maKh) {
        this.maKh = maKh;
    }

    
    @Column(name="TenKH", nullable=false)
    public String getTenKh() {
        return this.tenKh;
    }
    
    public void setTenKh(String tenKh) {
        this.tenKh = tenKh;
    }

    
    @Column(name="SDT", nullable=false, length=20)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khachHang")
    public Set<DatBan> getDatBans() {
        return this.datBans;
    }
    
    public void setDatBans(Set<DatBan> datBans) {
        this.datBans = datBans;
    }




}


