package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable ;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KhuyenMai generated by hbm2java
 */
@Entity
@Table(name="KhuyenMai"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class KhuyenMai  implements java.io.Serializable  {


     private String maKm;
     private String tenKm;
     private int giam;
     private Set<Duockhuyenmai> duockhuyenmais = new HashSet<Duockhuyenmai>(0);

    public KhuyenMai() {
    }

	
    public KhuyenMai(String maKm, String tenKm, int giam) {
        this.maKm = maKm;
        this.tenKm = tenKm;
        this.giam = giam;
    }
    public KhuyenMai(String maKm, String tenKm, int giam, Set<Duockhuyenmai> duockhuyenmais) {
       this.maKm = maKm;
       this.tenKm = tenKm;
       this.giam = giam;
       this.duockhuyenmais = duockhuyenmais;
    }
   
     @Id 

    
    @Column(name="MaKM", unique=true, nullable=false, length=5)
    public String getMaKm() {
        return this.maKm;
    }
    
    public void setMaKm(String maKm) {
        this.maKm = maKm;
    }

    
    @Column(name="TenKM", nullable=false)
    public String getTenKm() {
        return this.tenKm;
    }
    
    public void setTenKm(String tenKm) {
        this.tenKm = tenKm;
    }

    
    @Column(name="Giam", nullable=false)
    public int getGiam() {
        return this.giam;
    }
    
    public void setGiam(int giam) {
        this.giam = giam;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khuyenMai")
    public Set<Duockhuyenmai> getDuockhuyenmais() {
        return this.duockhuyenmais;
    }
    
    public void setDuockhuyenmais(Set<Duockhuyenmai> duockhuyenmais) {
        this.duockhuyenmais = duockhuyenmais;
    }




}


