package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable ;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loai generated by hbm2java
 */
@Entity
@Table(name="Loai"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class Loai  implements java.io.Serializable  {


     private String maLoai;
     private String tenLoai;
     private Set<Monan> monans = new HashSet<Monan>(0);

    public Loai() {
    }

	
    public Loai(String maLoai, String tenLoai) {
        this.maLoai = maLoai;
        this.tenLoai = tenLoai;
    }
    public Loai(String maLoai, String tenLoai, Set<Monan> monans) {
       this.maLoai = maLoai;
       this.tenLoai = tenLoai;
       this.monans = monans;
    }
   
     @Id 

    
    @Column(name="MaLoai", unique=true, nullable=false, length=10)
    public String getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(String maLoai) {
        this.maLoai = maLoai;
    }

    
    @Column(name="TenLoai", nullable=false)
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loai")
    public Set<Monan> getMonans() {
        return this.monans;
    }
    
    public void setMonans(Set<Monan> monans) {
        this.monans = monans;
    }




}


