package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable ;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nguyenlieu generated by hbm2java
 */
@Entity
@Table(name="NGUYENLIEU"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class Nguyenlieu  implements java.io.Serializable  {


     private String maNl;
     private Nhacungcap nhacungcap;
     private String tenNl;
     private String donVi;
     private BigDecimal donGia;
     private int soLuong;
     private Set<Chitiethoadonnhap> chitiethoadonnhaps = new HashSet<Chitiethoadonnhap>(0);

    public Nguyenlieu() {
    }

	
    public Nguyenlieu(String maNl, Nhacungcap nhacungcap, String tenNl, String donVi, BigDecimal donGia, int soLuong) {
        this.maNl = maNl;
        this.nhacungcap = nhacungcap;
        this.tenNl = tenNl;
        this.donVi = donVi;
        this.donGia = donGia;
        this.soLuong = soLuong;
    }
    public Nguyenlieu(String maNl, Nhacungcap nhacungcap, String tenNl, String donVi, BigDecimal donGia, int soLuong, Set<Chitiethoadonnhap> chitiethoadonnhaps) {
       this.maNl = maNl;
       this.nhacungcap = nhacungcap;
       this.tenNl = tenNl;
       this.donVi = donVi;
       this.donGia = donGia;
       this.soLuong = soLuong;
       this.chitiethoadonnhaps = chitiethoadonnhaps;
    }
   
     @Id 

    
    @Column(name="MaNL", unique=true, nullable=false, length=5)
    public String getMaNl() {
        return this.maNl;
    }
    
    public void setMaNl(String maNl) {
        this.maNl = maNl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaNCC", nullable=false)
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }

    
    @Column(name="TenNL", nullable=false)
    public String getTenNl() {
        return this.tenNl;
    }
    
    public void setTenNl(String tenNl) {
        this.tenNl = tenNl;
    }

    
    @Column(name="DonVi", nullable=false)
    public String getDonVi() {
        return this.donVi;
    }
    
    public void setDonVi(String donVi) {
        this.donVi = donVi;
    }

    
    @Column(name="DonGia", nullable=false, scale=4)
    public BigDecimal getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }

    
    @Column(name="SoLuong", nullable=false)
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nguyenlieu")
    public Set<Chitiethoadonnhap> getChitiethoadonnhaps() {
        return this.chitiethoadonnhaps;
    }
    
    public void setChitiethoadonnhaps(Set<Chitiethoadonnhap> chitiethoadonnhaps) {
        this.chitiethoadonnhaps = chitiethoadonnhaps;
    }




}


