package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable ;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name="NHACUNGCAP"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class Nhacungcap  implements java.io.Serializable  {


     private String maNcc;
     private String tenNcc;
     private String diaChi;
     private String sdt;
     private Set<Nguyenlieu> nguyenlieus = new HashSet<Nguyenlieu>(0);

    public Nhacungcap() {
    }

	
    public Nhacungcap(String maNcc, String tenNcc, String diaChi, String sdt) {
        this.maNcc = maNcc;
        this.tenNcc = tenNcc;
        this.diaChi = diaChi;
        this.sdt = sdt;
    }
    public Nhacungcap(String maNcc, String tenNcc, String diaChi, String sdt, Set<Nguyenlieu> nguyenlieus) {
       this.maNcc = maNcc;
       this.tenNcc = tenNcc;
       this.diaChi = diaChi;
       this.sdt = sdt;
       this.nguyenlieus = nguyenlieus;
    }
   
     @Id 

    
    @Column(name="MaNCC", unique=true, nullable=false, length=5)
    public String getMaNcc() {
        return this.maNcc;
    }
    
    public void setMaNcc(String maNcc) {
        this.maNcc = maNcc;
    }

    
    @Column(name="TenNCC", nullable=false)
    public String getTenNcc() {
        return this.tenNcc;
    }
    
    public void setTenNcc(String tenNcc) {
        this.tenNcc = tenNcc;
    }

    
    @Column(name="DiaChi", nullable=false)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="SDT", nullable=false, length=20)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhacungcap")
    public Set<Nguyenlieu> getNguyenlieus() {
        return this.nguyenlieus;
    }
    
    public void setNguyenlieus(Set<Nguyenlieu> nguyenlieus) {
        this.nguyenlieus = nguyenlieus;
    }




}


