package Model_Hiber;
// Generated Apr 19, 2023 8:08:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable ;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name="NhanVien"
    ,schema="dbo"
    ,catalog="QUANLYNHAHANG_JAVA_D12"
)
public class NhanVien  implements java.io.Serializable  {


     private String maNv;
     private DangNhap dangNhap;
     private String hoTen;
     private String sdt;
     private String cccd;
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);
     private Set<Hoadonnhap> hoadonnhaps = new HashSet<Hoadonnhap>(0);

    public NhanVien() {
        
    }

	
    public NhanVien(String maNv, DangNhap dangNhap, String hoTen, String sdt, String cccd) {
        this.maNv = maNv;
        this.dangNhap = dangNhap;
        this.hoTen = hoTen;
        this.sdt = sdt;
        this.cccd = cccd;
    }
    public NhanVien(String maNv, DangNhap dangNhap, String hoTen, String sdt, String cccd, Set<HoaDon> hoaDons, Set<Hoadonnhap> hoadonnhaps) {
       this.maNv = maNv;
       this.dangNhap = dangNhap;
       this.hoTen = hoTen;
       this.sdt = sdt;
       this.cccd = cccd;
       this.hoaDons = hoaDons;
       this.hoadonnhaps = hoadonnhaps;
    }
   
     @Id 

    
    @Column(name="MaNV", unique=true, nullable=false, length=5)
    public String getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(String maNv) {
        this.maNv = maNv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaDangNhap", nullable=false)
    public DangNhap getDangNhap() {
        return this.dangNhap;
    }
    
    public void setDangNhap(DangNhap dangNhap) {
        this.dangNhap = dangNhap;
    }

    
    @Column(name="HoTen", nullable=false)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="SDT", nullable=false, length=15)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    
    @Column(name="CCCD", nullable=false, length=20)
    public String getCccd() {
        return this.cccd;
    }
    
    public void setCccd(String cccd) {
        this.cccd = cccd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanVien")
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanVien")
    public Set<Hoadonnhap> getHoadonnhaps() {
        return this.hoadonnhaps;
    }
    
    public void setHoadonnhaps(Set<Hoadonnhap> hoadonnhaps) {
        this.hoadonnhaps = hoadonnhaps;
    }




}


