/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.PhanQuyenNV;
import java.awt.Desktop;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author admin
 */
public class frmTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangChu
     */
    public frmTrangChu() {
        initComponents();
       loadMenu();
       
     if (!PhanQuyenNV.getTenNV().equals("Admin")) {
            jmenuNhapHang.setEnabled(false);
            jmenuQL.setEnabled(false);
        }
       // KT();
        
    }
   public  JDesktopPane getJDesk3() {
        return DesktopPane3;
    }
    
 
   public  JDesktopPane getJDesk1() {
        return DesktopLayout1;
    }

   
   public void loadThucDon()
    {
        DesktopLayout1.removeAll();
        frmMenu frm = new frmMenu(frmTrangChu.this);
        DesktopLayout1.add(frm);
        frm.pack(); 
        frm.setVisible(true);
    }
    
    
    public void loadMenu()
    {DesktopLayout1.removeAll();
        frmMenu frm = new frmMenu(frmTrangChu.this);
        DesktopLayout1.add(frm);
        frm.pack(); 
        frm.setVisible(true);
        
        
        DesktopPane2.removeAll();
        frmDatBan frmDB = new frmDatBan(this);
        DesktopPane2.add(frmDB);
        frmDB.pack(); 
        frmDB.setVisible(true);
        
        DesktopPane3.removeAll();
        frmNone frmN = new frmNone();
        DesktopPane3.add(frmN);
        frmN.pack(); 
        frmN.setVisible(true);
      
    }
    
    
    void KT()
    {
         JInternalFrame[] frames = DesktopPane3.getAllFrames();
        for (JInternalFrame frame : frames) {
            if (frame.getTitle().equals("HoaDon")) {
                JOptionPane.showMessageDialog(null, "hihi");
               
            }
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        DesktopPane3 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        DesktopLayout1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        DesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuQL = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuBieuDoTron = new javax.swing.JMenuItem();
        jmenuNhapHang = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem4.setText("jMenuItem4");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 111, 60));

        DesktopPane3.setBackground(new java.awt.Color(255, 111, 60));

        javax.swing.GroupLayout DesktopPane3Layout = new javax.swing.GroupLayout(DesktopPane3);
        DesktopPane3.setLayout(DesktopPane3Layout);
        DesktopPane3Layout.setHorizontalGroup(
            DesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        DesktopPane3Layout.setVerticalGroup(
            DesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane3)
        );

        jPanel2.setBackground(new java.awt.Color(232, 106, 51));

        javax.swing.GroupLayout DesktopLayout1Layout = new javax.swing.GroupLayout(DesktopLayout1);
        DesktopLayout1.setLayout(DesktopLayout1Layout);
        DesktopLayout1Layout.setHorizontalGroup(
            DesktopLayout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        DesktopLayout1Layout.setVerticalGroup(
            DesktopLayout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopLayout1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopLayout1)
        );

        jPanel3.setBackground(new java.awt.Color(255, 154, 60));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout DesktopPane2Layout = new javax.swing.GroupLayout(DesktopPane2);
        DesktopPane2.setLayout(DesktopPane2Layout);
        DesktopPane2Layout.setHorizontalGroup(
            DesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        DesktopPane2Layout.setVerticalGroup(
            DesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane2)
        );

        jmenuQL.setText("Quản lý");
        jmenuQL.setMargin(new java.awt.Insets(0, 20, 0, 20));

        jMenuItem1.setText("Thực đơn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmenuQL.add(jMenuItem1);

        jMenuItem2.setText("Nhân viên");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmenuQL.add(jMenuItem2);

        jMenuBar1.add(jmenuQL);

        jMenu4.setText("Thống kê");
        jMenu4.setMargin(new java.awt.Insets(0, 20, 0, 20));

        menuBieuDoTron.setText("Biểu đồ");
        menuBieuDoTron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBieuDoTronActionPerformed(evt);
            }
        });
        jMenu4.add(menuBieuDoTron);

        jMenuBar1.add(jMenu4);

        jmenuNhapHang.setText("Nhập hàng");

        jMenuItem5.setText("Hàng hóa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmenuNhapHang.add(jMenuItem5);

        jMenuBar1.add(jmenuNhapHang);

        jMenu5.setText("Khác");
        jMenu5.setMargin(new java.awt.Insets(0, 20, 0, 20));

        jMenuItem9.setText("Đăng xuất");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmThucDon td= new frmThucDon(frmTrangChu.this);
        td.pack();
        td.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuBieuDoTronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBieuDoTronActionPerformed
        DesktopPane3.removeAll();
        frmBieuDoTron frmChart1 = new frmBieuDoTron(this);
        DesktopPane3.add(frmChart1);
        frmChart1.pack(); 
        frmChart1.setVisible(true);
    }//GEN-LAST:event_menuBieuDoTronActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        // TODO add your handling code here:
        frmNhanVien frmNV= new frmNhanVien();
         frmNV.pack();
       frmNV.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        frmNhapHang frm = new frmNhapHang();
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmDangNhap frm = new frmDangNhap();
        frm.pack();
        frm.setVisible(true);
        
             
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopLayout1;
    private javax.swing.JDesktopPane DesktopPane2;
    private javax.swing.JDesktopPane DesktopPane3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu jmenuNhapHang;
    private javax.swing.JMenu jmenuQL;
    private javax.swing.JMenuItem menuBieuDoTron;
    // End of variables declaration//GEN-END:variables
}
