/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAL.dal_BanAn;
import DAL.dal_HoaDon;
import Model.PhanQuyenNV;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author admin
 */
public class frmTrangThai_Dat extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangThai_Dat
     */
    String tenkh;
    String sdt;
    int sl;
    String ngaydat;
    String madb;
    String tenban;
    frmDatBan frmdb;
    
    public frmTrangThai_Dat(String ten, String sdt, int sl, String ngay,String MaDB,String tenban,frmDatBan frmdb) {
        initComponents();
        setLocationRelativeTo(null) ;
        lbMaDB.setVisible(false);
        this.frmdb=frmdb;
        this.tenkh=ten;
        this.sdt=sdt;
        this.sl=sl;
        this.tenban=tenban;
        this.ngaydat=ngay;
        this.madb=MaDB;
        loadData();
    }
    
     public frmTrangThai_Dat() {
         initComponents();
         
    }
    
    void loadData()
    {
         JOptionPane.showMessageDialog(null, "Xin chào!");
        lbTenKH.setText(tenkh);
        lbSDT.setText(sdt);
        lbSoLuong.setText(String.valueOf(sl));
        lbNgay.setText(ngaydat);
        lbMaDB.setText(madb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnGoiMon = new javax.swing.JButton();
        btnHuyBan = new javax.swing.JButton();
        lbTenKH = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        lbMaDB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 211, 193));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Thông tin đặt bàn");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Tên khách hàng:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Số điện thoại:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Số lượng khách:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Ngày:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        btnGoiMon.setText("Gọi món");
        btnGoiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiMonActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoiMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        btnHuyBan.setText("Hủy bàn");
        btnHuyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBanActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuyBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        lbTenKH.setText("####");
        jPanel1.add(lbTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        lbSDT.setText("####");
        jPanel1.add(lbSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        lbSoLuong.setText("####");
        jPanel1.add(lbSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        lbNgay.setText("####");
        jPanel1.add(lbNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        lbMaDB.setText("####");
        jPanel1.add(lbMaDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/depositphotos_41833689-stock-illustration-seamless-food-background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
 
    private void btnGoiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiMonActionPerformed
            //Tạo hóa đơn:
            Date currentDate = new Date();
       
            String tennv= PhanQuyenNV.getTenNV();
            dal_HoaDon.insertHoaDon(currentDate,"Chưa thanh toán",tennv,tenban);
            JOptionPane.showMessageDialog(null, "Chúc quý khách ăn ngon miệng");
            frmdb.loadSoDoBanAn();
            frmdb.HienthiHD(tenban);
            this.dispose();
            
    }//GEN-LAST:event_btnGoiMonActionPerformed

    private void btnHuyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBanActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn hủy bàn ăn này không??", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int ketqua=dal_BanAn.delBanDat(lbMaDB.getText());
            if(ketqua!=0)
            {
               JOptionPane.showMessageDialog(null, "Hủy thành công");
              //  frmDatBan frm1 = new frmDatBan(ketqua);
              frmdb.loadSoDoBanAn();
                this.dispose();
                
                        
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Hủy không thành công");
                frmdb.loadSoDoBanAn();
                //frmDatBan frm1 = new frmDatBan(ketqua);
                this.dispose();
            }
            
        } else {
            this.dispose();
        }
        
    }//GEN-LAST:event_btnHuyBanActionPerformed


   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangThai_Dat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangThai_Dat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangThai_Dat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangThai_Dat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangThai_Dat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoiMon;
    private javax.swing.JButton btnHuyBan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbMaDB;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenKH;
    // End of variables declaration//GEN-END:variables
}
